name: Publish Dependency
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  call-reusable-workflow:
    uses: intisy/workflows/.github/workflows/publish-dependency.yml@main
    with:
      repository: ${{ github.repository }}
    secrets:
      envPAT: ${{ secrets.PAT }}